import { mapEnumToOptions } from '@abp/ng.core';

export enum NotificationType {
  EnrollmentApproved = 0,
  EnrollmentRejected = 1,
  EnrollmentRequestPending = 2,
  ParentStudentLinked = 3,
  ExamGradePosted = 4,
  AttendanceMarkedAbsent = 5,
  AttendanceMarkedPresent = 6,
  SecretaryLinkRequestSent = 7,
  SecretaryLinkRequestApproved = 8,
  SecretaryLinkRequestRejected = 9,
  General = 10,
  AcademyJoinRequestPending = 11,
  AcademyJoinRequestApproved = 12,
  AcademyJoinRequestRejected = 13,
  SessionStarted = 14,
  SessionMessage = 15,
  PasswordResetRequested = 16,
  PasswordResetCompleted = 17,
  AcademyCourseTeacherAssigned = 18,
  AcademyCourseTeacherRequestPending = 19,
  AcademyCourseTeacherApproved = 20,
  AcademyCourseTeacherRejected = 21,
  PromotionRequestPending = 22,
  PromotionRequestApproved = 23,
  PromotionRequestRejected = 24,
  GroupChangeRequestPending = 25,
  GroupChangeRequestApproved = 26,
  GroupChangeRequestRejected = 27,
  RegistrationRequestPending = 28,
  RegistrationRequestApproved = 29,
  RegistrationRequestRejected = 30,
}

export const notificationTypeOptions = mapEnumToOptions(NotificationType);
